name: CI

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    name: "PHPUnit (PHP ${{ matrix.php }})"
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with latest composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"

      - name: Run unit tests
        run: vendor/bin/phpunit


  code-quality:
    name: Check ${{ matrix.tool }} (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']
        tool: ['phpstan', 'code-coverage']

        include:
          - php: '8.3'
            tool: 'code-style'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          extensions: mbstring
          coverage: xdebug

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"

      - name: Run static code analysis
        if: ${{ matrix.tool == 'phpstan' }}
        run: composer run phpstan -- --error-format=github

      - name: Run tests with coverage-clover
        if: ${{ matrix.tool == 'code-coverage' }}
        run: composer run phpunit -- --coverage-clover .phpunit.cache/clover.xml

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.tool == 'code-coverage' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./clover.xml
          fail_ci_if_error: true
          verbose: true

      - name: Check code-style
        if: ${{ matrix.tool == 'code-style' }}
        run: composer run codestyle -- --dry-run --diff
