name: CI

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']

    name: "PHPStan on PHP ${{ matrix.php }}"
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with latest composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: none
          tools: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        coverage: [false]

        include:
          ## Run code coverage on highest supported PHP version.
          - php: '8.2'
            coverage: true

    name: "PHPUnit on PHP ${{ matrix.php }}"
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with latest composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
          tools: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"

      - name: Run unit tests without code coverage
        if: ${{ matrix.coverage == false }}
        run: vendor/bin/phpunit

      - name: Run unit tests with code coverage
        if: ${{ matrix.coverage == true }}
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Send coverage report to Codecov
        if: ${{ success() && matrix.coverage == true }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./clover.xml
          fail_ci_if_error: true
          verbose: true
